context:
  name: cuid
  version: "0.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 74eaba154916a2240405c3631acee708c263ef8fa05a86820b87d0f59f84e978

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - cuid
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Fast, scalable unique ID generation
  homepage: https://github.com/necaris/cuid.py
  repository: https://github.com/necaris/cuid.py

extra:
  recipe-maintainers:
    - timkpaine
